version: 3

tasks:

  build.client:
    dir: .
    cmds:
      - pnpm build

  build.core:
    dir: ./server/netvox_core
    cmds:
      - deno_bindgen --release="."
      - deno task prepare
      - cargo about generate -c ./about.toml ./about.hbs -o ../../build/third/LICENSE.netvox_core.html

  build:
    dir: ./server
    deps:
      - build.core
      - build.client
    cmds:
      - deno compile -A -o ../build/netvox.exe --unstable-ffi --include ./src/worker.ts ./src/main.ts
